export const testData = () => {
    const rawData = {
        0: {
            "1": [
                {
                    id: 0,
                    criteria: "criterion 1",
                    weight: 5,
                    alt1: 9,
                    alt2: 5,
                    alt3: 5,
                    alt4: 3,
                    alt5: 7,
                    alt6: 9,
                },
                {
                    id: 1,
                    criteria: "criterion 2",
                    weight: 9,
                    alt1: 9,
                    alt2: 5,
                    alt3: 9,
                    alt4: 7,
                    alt5: 3,
                    alt6: 9,
                },
                {
                    id: 2,
                    criteria: "criterion 3",
                    weight: 7,
                    alt1: 7,
                    alt2: 7,
                    alt3: 5,
                    alt4: 7,
                    alt5: 3,
                    alt6: 3,
                },
                {
                    id: 3,
                    criteria: "criterion 4",
                    weight: 3,
                    alt1: 9,
                    alt2: 7,
                    alt3: 7,
                    alt4: 7,
                    alt5: 7,
                    alt6: 1,
                },
                {
                    id: 4,
                    criteria: "criterion 5",
                    weight: 5,
                    alt1: 7,
                    alt2: 3,
                    alt3: 3,
                    alt4: 7,
                    alt5: 5,
                    alt6: 5,
                }
            ],
            "2": [
                {
                    id: 0,
                    criteria: "criterion 1",
                    weight: 3,
                    alt1: 9,
                    alt2: 3,
                    alt3: 3,
                    alt4: 7,
                    alt5: 5,
                    alt6: 1,
                },
                {
                    id: 1,
                    criteria: "criterion 2",
                    weight: 7,
                    alt1: 1,
                    alt2: 9,
                    alt3: 3,
                    alt4: 5,
                    alt5: 5,
                    alt6: 1,
                },
                {
                    id: 2,
                    criteria: "criterion 3",
                    weight: 9,
                    alt1: 3,
                    alt2: 3,
                    alt3: 9,
                    alt4: 1,
                    alt5: 5,
                    alt6: 9,
                },
                {
                    id: 3,
                    criteria: "criterion 4",
                    weight: 5,
                    alt1: 9,
                    alt2: 5,
                    alt3: 5,
                    alt4: 7,
                    alt5: 5,
                    alt6: 7,
                },
                {
                    id: 4,
                    criteria: "criterion 5",
                    weight: 5,
                    alt1: 1,
                    alt2: 9,
                    alt3: 3,
                    alt4: 9,
                    alt5: 5,
                    alt6: 9,
                }
            ],
            "3": [
                {
                    id: 0,
                    criteria: "criterion 1",
                    weight: 5,
                    alt1: 9,
                    alt2: 3,
                    alt3: 3,
                    alt4: 7,
                    alt5: 3,
                    alt6: 3,
                },
                {
                    id: 1,
                    criteria: "criterion 2",
                    weight: 7,
                    alt1: 5,
                    alt2: 3,
                    alt3: 9,
                    alt4: 5,
                    alt5: 7,
                    alt6: 9,
                },
                {
                    id: 2,
                    criteria: "criterion 3",
                    weight: 7,
                    alt1: 3,
                    alt2: 3,
                    alt3: 5,
                    alt4: 5,
                    alt5: 5,
                    alt6: 7,
                },
                {
                    id: 3,
                    criteria: "criterion 4",
                    weight: 5,
                    alt1: 7,
                    alt2: 3,
                    alt3: 5,
                    alt4: 7,
                    alt5: 9,
                    alt6: 3,
                },
                {
                    id: 4,
                    criteria: "criterion 5",
                    weight: 9,
                    alt1: 5,
                    alt2: 3,
                    alt3: 7,
                    alt4: 5,
                    alt5: 7,
                    alt6: 3,
                }
            ]

        }

    }

    // Convert data object to an array of rows
    //const resultArray = Object.values(rawData.data).flat();

    return {
                0: {
            "1": [
                {
                    id: 0,
                    criteria: "criterion 1",
                    weight: 5,
                    alt1: 9,
                    alt2: 5,
                    alt3: 5,
                    alt4: 3,
                    alt5: 7,
                    alt6: 9,
                },
                {
                    id: 1,
                    criteria: "criterion 2",
                    weight: 9,
                    alt1: 9,
                    alt2: 5,
                    alt3: 9,
                    alt4: 7,
                    alt5: 3,
                    alt6: 9,
                },
                {
                    id: 2,
                    criteria: "criterion 3",
                    weight: 7,
                    alt1: 7,
                    alt2: 7,
                    alt3: 5,
                    alt4: 7,
                    alt5: 3,
                    alt6: 3,
                },
                {
                    id: 3,
                    criteria: "criterion 4",
                    weight: 3,
                    alt1: 9,
                    alt2: 7,
                    alt3: 7,
                    alt4: 7,
                    alt5: 7,
                    alt6: 1,
                },
                {
                    id: 4,
                    criteria: "criterion 5",
                    weight: 5,
                    alt1: 7,
                    alt2: 3,
                    alt3: 3,
                    alt4: 7,
                    alt5: 5,
                    alt6: 5,
                }
            ],
            "2": [
                {
                    id: 0,
                    criteria: "criterion 1",
                    weight: 3,
                    alt1: 9,
                    alt2: 3,
                    alt3: 3,
                    alt4: 7,
                    alt5: 5,
                    alt6: 1,
                },
                {
                    id: 1,
                    criteria: "criterion 2",
                    weight: 7,
                    alt1: 1,
                    alt2: 9,
                    alt3: 3,
                    alt4: 5,
                    alt5: 5,
                    alt6: 1,
                },
                {
                    id: 2,
                    criteria: "criterion 3",
                    weight: 9,
                    alt1: 3,
                    alt2: 3,
                    alt3: 9,
                    alt4: 1,
                    alt5: 5,
                    alt6: 9,
                },
                {
                    id: 3,
                    criteria: "criterion 4",
                    weight: 5,
                    alt1: 9,
                    alt2: 5,
                    alt3: 5,
                    alt4: 7,
                    alt5: 5,
                    alt6: 7,
                },
                {
                    id: 4,
                    criteria: "criterion 5",
                    weight: 5,
                    alt1: 1,
                    alt2: 9,
                    alt3: 3,
                    alt4: 9,
                    alt5: 5,
                    alt6: 9,
                }
            ],
            "3": [
                {
                    id: 0,
                    criteria: "criterion 1",
                    weight: 5,
                    alt1: 9,
                    alt2: 3,
                    alt3: 3,
                    alt4: 7,
                    alt5: 3,
                    alt6: 3,
                },
                {
                    id: 1,
                    criteria: "criterion 2",
                    weight: 7,
                    alt1: 5,
                    alt2: 3,
                    alt3: 9,
                    alt4: 5,
                    alt5: 7,
                    alt6: 9,
                },
                {
                    id: 2,
                    criteria: "criterion 3",
                    weight: 7,
                    alt1: 3,
                    alt2: 3,
                    alt3: 5,
                    alt4: 5,
                    alt5: 5,
                    alt6: 7,
                },
                {
                    id: 3,
                    criteria: "criterion 4",
                    weight: 5,
                    alt1: 7,
                    alt2: 3,
                    alt3: 5,
                    alt4: 7,
                    alt5: 9,
                    alt6: 3,
                },
                {
                    id: 4,
                    criteria: "criterion 5",
                    weight: 9,
                    alt1: 5,
                    alt2: 3,
                    alt3: 7,
                    alt4: 5,
                    alt5: 7,
                    alt6: 3,
                }
            ]

        }
        /*Object: {
            data: resultArray
        }
         */
    }
};